version: "3"
services:
  postgres:
    image: postgres:11.2
    container_name: "express_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"